-- Directory + categories + saved professionals + messaging improvements
-- Notes:
-- - No fake users/professionals/reviews are seeded.
-- - Categories are a static taxonomy; safe to seed separately if desired.

-- Directory (public fields only; no email/phone)
create table if not exists public.professional_directory (
  id uuid primary key references public.professional_profiles(id) on delete cascade,
  first_name text not null default '',
  last_name text not null default '',
  province_code text references public.provinces(code),
  headline text,
  bio text,
  specializations text[] not null default '{}',
  avatar_url text,
  cover_url text,
  available_remote boolean not null default false,
  available_travel boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.professional_directory enable row level security;
alter table public.professional_directory force row level security;

create table if not exists public.customer_directory (
  id uuid primary key references public.profiles(id) on delete cascade,
  first_name text not null default '',
  last_name text not null default '',
  province_code text references public.provinces(code),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.customer_directory enable row level security;
alter table public.customer_directory force row level security;

-- Professional availability flags used by search filters
alter table public.professional_profiles
  add column if not exists available_remote boolean not null default false,
  add column if not exists available_travel boolean not null default false;

-- Conversation preview helpers
alter table public.conversations
  add column if not exists last_message_body text,
  add column if not exists last_message_sender_id uuid references public.profiles(id) on delete set null;

-- Saved professionals (customer bookmarks)
create table if not exists public.saved_professionals (
  customer_id uuid not null references public.profiles(id) on delete cascade,
  professional_id uuid not null references public.professional_profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (customer_id, professional_id)
);

alter table public.saved_professionals enable row level security;
alter table public.saved_professionals force row level security;

-- Categories (taxonomy)
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  image_url text,
  created_at timestamptz not null default now()
);

alter table public.categories enable row level security;
alter table public.categories force row level security;

create table if not exists public.professional_categories (
  professional_id uuid not null references public.professional_profiles(id) on delete cascade,
  category_id bigint not null references public.categories(id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (professional_id, category_id)
);

alter table public.professional_categories enable row level security;
alter table public.professional_categories force row level security;

-- Helpers: can a professional see a customer directory row?
create or replace function public.professional_can_view_customer_dir(customer_uuid uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.conversations c
    where c.professional_id = auth.uid()
      and c.customer_id = customer_uuid
  ) or (select public.is_admin());
$$;

-- Keep directory tables in sync (public fields only)
create or replace function public.tg_profiles_sync_directories()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  -- NOTE: professional_directory references professional_profiles, which may not exist
  -- yet when a profile row is inserted (signup trigger creates profiles first).
  -- professional_directory is synced from professional_profiles triggers instead.
  if new.role = 'customer' then
    insert into public.customer_directory (id, first_name, last_name, province_code)
    values (new.id, new.first_name, new.last_name, new.province_code)
    on conflict (id) do update
      set first_name = excluded.first_name,
          last_name = excluded.last_name,
          province_code = excluded.province_code,
          updated_at = now();
  elsif new.role = 'professional' then
    update public.professional_directory
    set first_name = new.first_name,
        last_name = new.last_name,
        province_code = new.province_code,
        updated_at = now()
    where id = new.id;
  end if;

  return new;
end;
$$;

drop trigger if exists profiles_sync_directories on public.profiles;
create trigger profiles_sync_directories
after insert or update of first_name, last_name, province_code, role
on public.profiles
for each row execute function public.tg_profiles_sync_directories();

create or replace function public.tg_professional_profiles_sync_directory()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.professional_directory (
    id,
    headline,
    bio,
    specializations,
    avatar_url,
    cover_url,
    available_remote,
    available_travel
  )
  values (
    new.id,
    new.headline,
    new.bio,
    new.specializations,
    new.avatar_url,
    new.cover_url,
    coalesce(new.available_remote, false),
    coalesce(new.available_travel, false)
  )
  on conflict (id) do update
    set headline = excluded.headline,
        bio = excluded.bio,
        specializations = excluded.specializations,
        avatar_url = excluded.avatar_url,
        cover_url = excluded.cover_url,
        available_remote = excluded.available_remote,
        available_travel = excluded.available_travel,
        updated_at = now();

  return new;
end;
$$;

drop trigger if exists professional_profiles_sync_directory on public.professional_profiles;
create trigger professional_profiles_sync_directory
after insert or update of headline, bio, specializations, avatar_url, cover_url, available_remote, available_travel
on public.professional_profiles
for each row execute function public.tg_professional_profiles_sync_directory();

-- Ensure new professionals have directory rows even if the order of triggers changes.
create or replace function public.tg_ensure_professional_directory_row()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  prof public.profiles%rowtype;
begin
  select *
  into prof
  from public.profiles p
  where p.id = new.id;

  if prof.role = 'professional' then
    insert into public.professional_directory (id, first_name, last_name, province_code)
    values (new.id, prof.first_name, prof.last_name, prof.province_code)
    on conflict (id) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists ensure_professional_directory_row on public.professional_profiles;
create trigger ensure_professional_directory_row
after insert on public.professional_profiles
for each row execute function public.tg_ensure_professional_directory_row();

-- Update timestamps on directory tables
drop trigger if exists set_professional_directory_updated_at on public.professional_directory;
create trigger set_professional_directory_updated_at
before update on public.professional_directory
for each row execute function public.tg_set_updated_at();

drop trigger if exists set_customer_directory_updated_at on public.customer_directory;
create trigger set_customer_directory_updated_at
before update on public.customer_directory
for each row execute function public.tg_set_updated_at();

-- Contact request trigger: create conversation AND initial message (so chat is real from day 1)
create or replace function public.tg_contact_request_create_conversation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  conv_id uuid;
begin
  insert into public.conversations (request_id, customer_id, professional_id, status)
  values (new.id, new.customer_id, new.professional_id, new.status)
  on conflict (request_id) do update
    set status = excluded.status
  returning id into conv_id;

  insert into public.messages (conversation_id, sender_id, body)
  values (conv_id, new.customer_id, new.message);

  return new;
end;
$$;

-- Message trigger: keep conversation preview fields in sync
create or replace function public.tg_message_set_last_message_at()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.conversations
  set last_message_at = new.created_at,
      last_message_body = new.body,
      last_message_sender_id = new.sender_id
  where id = new.conversation_id;

  return new;
end;
$$;

-- RLS POLICIES

-- Directory: professionals can browse all; customers only active subscribers
drop policy if exists "Professional directory: professionals read" on public.professional_directory;
create policy "Professional directory: professionals read"
on public.professional_directory
for select
to authenticated
using ((select public.is_professional()) or (select public.is_admin()));

drop policy if exists "Professional directory: customers read active only" on public.professional_directory;
create policy "Professional directory: customers read active only"
on public.professional_directory
for select
to authenticated
using (
  (select public.is_customer())
  and (select public.professional_is_active_subscriber(public.professional_directory.id))
);

drop policy if exists "Professional directory: owner update" on public.professional_directory;
create policy "Professional directory: owner update"
on public.professional_directory
for update
to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

drop policy if exists "Professional directory: admin update" on public.professional_directory;
create policy "Professional directory: admin update"
on public.professional_directory
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

-- Customers: visible to themselves; and to professionals they have a conversation with
drop policy if exists "Customer directory: self read" on public.customer_directory;
create policy "Customer directory: self read"
on public.customer_directory
for select
to authenticated
using (id = (select auth.uid()));

drop policy if exists "Customer directory: professional participant read" on public.customer_directory;
create policy "Customer directory: professional participant read"
on public.customer_directory
for select
to authenticated
using ((select public.professional_can_view_customer_dir(public.customer_directory.id)));

drop policy if exists "Customer directory: self update" on public.customer_directory;
create policy "Customer directory: self update"
on public.customer_directory
for update
to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

drop policy if exists "Customer directory: admin update" on public.customer_directory;
create policy "Customer directory: admin update"
on public.customer_directory
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

-- Saved professionals (customer bookmarks)
drop policy if exists "Saved professionals: customer read own" on public.saved_professionals;
create policy "Saved professionals: customer read own"
on public.saved_professionals
for select
to authenticated
using (customer_id = (select auth.uid()));

drop policy if exists "Saved professionals: customer insert own" on public.saved_professionals;
create policy "Saved professionals: customer insert own"
on public.saved_professionals
for insert
to authenticated
with check (
  (select public.is_customer())
  and customer_id = (select auth.uid())
  and (select public.professional_is_active_subscriber(professional_id))
);

drop policy if exists "Saved professionals: customer delete own" on public.saved_professionals;
create policy "Saved professionals: customer delete own"
on public.saved_professionals
for delete
to authenticated
using (customer_id = (select auth.uid()));

-- Categories readable by everyone (needed for dropdowns)
drop policy if exists "Categories are readable" on public.categories;
create policy "Categories are readable"
on public.categories
for select
to anon, authenticated
using (true);

drop policy if exists "Categories: admin manage" on public.categories;
create policy "Categories: admin manage"
on public.categories
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

-- Professional categories: professionals manage their own mappings; customers can read mappings for active subscribers
drop policy if exists "Professional categories: readable by professionals" on public.professional_categories;
create policy "Professional categories: readable by professionals"
on public.professional_categories
for select
to authenticated
using ((select public.is_professional()) or (select public.is_admin()));

drop policy if exists "Professional categories: readable by customers (active only)" on public.professional_categories;
create policy "Professional categories: readable by customers (active only)"
on public.professional_categories
for select
to authenticated
using (
  (select public.is_customer())
  and (select public.professional_is_active_subscriber(professional_id))
);

drop policy if exists "Professional categories: pro insert own" on public.professional_categories;
create policy "Professional categories: pro insert own"
on public.professional_categories
for insert
to authenticated
with check (
  (select public.is_professional())
  and professional_id = (select auth.uid())
);

drop policy if exists "Professional categories: pro delete own" on public.professional_categories;
create policy "Professional categories: pro delete own"
on public.professional_categories
for delete
to authenticated
using (
  (select public.is_professional())
  and professional_id = (select auth.uid())
);
